export const AGENT_RUN = {
  goal: "Reconcile yesterday's payment failures and open one summary thread",
  model: "tool-using agent · 6 tools · human approval on send",
  totalMs: 41_200,
  steps: [
    {
      phase: "plan",
      title: "Break the goal into checkable steps",
      detail:
        "Fetch failed payments → group by failure reason → enrich top reasons with customer tier → draft summary → request approval before posting.",
      tool: null,
      ms: 2_100,
      status: "ok",
    },
    {
      phase: "act",
      title: "Query payments API",
      detail: "GET /payments?status=failed&since=2026-08-05T00:00:00Z → 184 records",
      tool: "payments.list",
      ms: 3_400,
      status: "ok",
    },
    {
      phase: "check",
      title: "Validate record shape",
      detail: "184/184 records have failure_code. 7 records missing customer_id → flagged, not dropped.",
      tool: null,
      ms: 900,
      status: "ok",
    },
    {
      phase: "act",
      title: "Group by failure reason",
      detail: "insufficient_funds 91 · card_expired 44 · do_not_honor 31 · gateway_timeout 18",
      tool: "warehouse.query",
      ms: 5_600,
      status: "ok",
    },
    {
      phase: "act",
      title: "Enrich with customer tier",
      detail: "CRM lookup timed out after 8s.",
      tool: "crm.lookup",
      ms: 8_000,
      status: "error",
    },
    {
      phase: "check",
      title: "Decide: retry or degrade",
      detail:
        "Enrichment is optional for the summary. Retry once with a smaller batch, then continue without tiers if it fails again.",
      tool: null,
      ms: 1_200,
      status: "warn",
    },
    {
      phase: "act",
      title: "Retry enrichment (batched)",
      detail: "3 batches of 40 → 118/184 customers matched to a tier.",
      tool: "crm.lookup",
      ms: 6_900,
      status: "ok",
    },
    {
      phase: "act",
      title: "Draft the summary",
      detail:
        "Top cause is insufficient_funds (49%), concentrated in self-serve tier. gateway_timeout is the only cause trending up week over week.",
      tool: "llm.generate",
      ms: 4_800,
      status: "ok",
    },
    {
      phase: "check",
      title: "Verify every number against source",
      detail: "4 claims checked against the grouped query result. All match. No unsupported claims.",
      tool: "verify.claims",
      ms: 3_100,
      status: "ok",
    },
    {
      phase: "act",
      title: "Request human approval",
      detail: "Posting is a write action → paused for approval instead of sending.",
      tool: "slack.post",
      ms: 1_100,
      status: "gate",
    },
    {
      phase: "done",
      title: "Stopped at the approval gate",
      detail: "Draft ready, sources attached, run fully traced. Waiting on a human.",
      tool: null,
      ms: 4_100,
      status: "done",
    },
  ],
  evals: [
    { name: "Task completed", value: "Yes (to approval gate)", tone: "good" },
    { name: "Claims grounded in source", value: "4 / 4", tone: "good" },
    { name: "Tool failures recovered", value: "1 / 1", tone: "good" },
    { name: "Unapproved write actions", value: "0", tone: "good" },
    { name: "Wall clock", value: "41.2s", tone: "neutral" },
  ],
};
